[package]
name = "mkcert"
version = "0.1.0"
authors = ["Andreas Longo"]
license = "GPL-3.0-or-later"
repository = "https://github.com/andreaslongo/mkcert"
edition = "2021"

[dependencies]
clap = { version = "4.4.0", features = ["derive"] }
openssl = "0.10.56"
