[package]
name = "mkcert"
version = "0.1.0"
edition = "2021"
authors = ["Andreas Longo"]
license = "GPL-3.0-or-later"
repository = "https://github.com/andreaslongo/mkcert"

[dependencies]
anstream = "0.6.4"
clap = { version = "4.4.6", features = ["derive"] }
openssl = "0.10.57"
owo-colors = "3.5.0"
rpassword = "7.2.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_yaml = "0.9.25"
